apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: frontend-node
  ports:
  - protocol: TCP
    port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.port }}